"""Belgie - Modern authentication for FastAPI."""

__version__ = "0.1.0"

# Re-export everything from belgie.auth for convenience
from belgie.auth import (
    AccountProtocol,
    AlchemyAdapter,
    Auth,
    AuthenticationError,
    AuthorizationError,
    AuthSettings,
    BelgieError,
    ConfigurationError,
    CookieSettings,
    GoogleOAuthProvider,
    GoogleOAuthSettings,
    GoogleTokenResponse,
    GoogleUserInfo,
    InvalidStateError,
    OAuthError,
    OAuthStateProtocol,
    SessionExpiredError,
    SessionManager,
    SessionProtocol,
    SessionSettings,
    URLSettings,
    UserProtocol,
    generate_session_id,
    generate_state_token,
    parse_scopes,
    validate_scopes,
)

__all__ = [
    "AccountProtocol",
    "AlchemyAdapter",
    "Auth",
    "AuthSettings",
    "AuthenticationError",
    "AuthorizationError",
    "BelgieError",
    "ConfigurationError",
    "CookieSettings",
    "GoogleOAuthProvider",
    "GoogleOAuthSettings",
    "GoogleTokenResponse",
    "GoogleUserInfo",
    "InvalidStateError",
    "OAuthError",
    "OAuthStateProtocol",
    "SessionExpiredError",
    "SessionManager",
    "SessionProtocol",
    "SessionSettings",
    "URLSettings",
    "UserProtocol",
    "__version__",
    "generate_session_id",
    "generate_state_token",
    "parse_scopes",
    "validate_scopes",
]
