import { compile, type JSONSchema } from "json-schema-to-typescript";

export type ToolSchema = {
  name: string;
  inputSchema: Record<string, unknown>;
  outputSchema: Record<string, unknown> | null;
};

type NamedToolSchema = ToolSchema & {
  typeName: string;
};

const GENERATED_BANNER = "/* generated by `belgie generate`; do not edit */";

export async function generateTypes(tools: ToolSchema[]): Promise<string> {
  const namedTools = assignTypeNames(tools);
  const declarations: string[] = [];

  for (const tool of namedTools) {
    declarations.push(await compileSchema(tool.inputSchema, `${tool.typeName}Input`));
    if (tool.outputSchema !== null) {
      declarations.push(await compileSchema(tool.outputSchema, `${tool.typeName}Output`));
    }
  }

  const registry = [
    "export interface Tools {",
    ...namedTools.flatMap((tool) => [
      `  ${JSON.stringify(tool.name)}: {`,
      `    input: ${tool.typeName}Input;`,
      `    output: ${tool.outputSchema === null ? "undefined" : `${tool.typeName}Output`};`,
      "  };",
    ]),
    "}",
  ].join("\n");

  return `${GENERATED_BANNER}\n\n${declarations.join("\n\n")}\n\n${registry}\n`;
}

function assignTypeNames(tools: ToolSchema[]): NamedToolSchema[] {
  if (tools.length === 0) {
    throw new Error("Cannot generate types for an empty tool registry");
  }

  const sorted = [...tools].sort((left, right) =>
    left.name < right.name ? -1 : left.name > right.name ? 1 : 0,
  );
  const names = new Set<string>();
  const toolNames = new Set<string>();
  return sorted.map((tool) => {
    if (!tool.name) {
      throw new Error("Tool names must not be empty");
    }
    if (toolNames.has(tool.name)) {
      throw new Error(`Duplicate tool name ${JSON.stringify(tool.name)}`);
    }
    toolNames.add(tool.name);

    const baseName = toTypeName(tool.name);
    let typeName = baseName;
    let suffix = 2;
    while (names.has(typeName)) {
      typeName = `${baseName}${suffix}`;
      suffix += 1;
    }
    names.add(typeName);
    return { ...tool, typeName };
  });
}

async function compileSchema(schema: Record<string, unknown>, name: string): Promise<string> {
  const prepared = namespaceDefinitions(schema, name);
  prepared.title = name;
  const source = await compile(prepared as JSONSchema, name, {
    $refOptions: {
      resolve: {
        external: false,
        file: false,
        http: false,
      },
    },
    additionalProperties: false,
    bannerComment: "",
    declareExternallyReferenced: true,
    enableConstEnums: false,
    format: true,
    style: {
      bracketSpacing: true,
      printWidth: 100,
      semi: true,
      singleQuote: false,
      tabWidth: 2,
      trailingComma: "all",
      useTabs: false,
    },
    unreachableDefinitions: false,
    unknownAny: true,
  });
  return source.trim();
}

function namespaceDefinitions(schema: Record<string, unknown>, prefix: string): Record<string, unknown> {
  const definitions = getDefinitions(schema);
  const names = new Map<string, string>();
  const used = new Set<string>();

  for (const key of Object.keys(definitions).sort()) {
    const baseName = `${prefix}${toTypeName(key)}`;
    let name = baseName;
    let suffix = 2;
    while (used.has(name)) {
      name = `${baseName}${suffix}`;
      suffix += 1;
    }
    used.add(name);
    names.set(key, name);
  }

  const rewrite = (value: unknown): unknown => {
    if (Array.isArray(value)) {
      return value.map(rewrite);
    }
    if (!isRecord(value)) {
      return value;
    }

    const rewritten: Record<string, unknown> = {};
    for (const [key, item] of Object.entries(value)) {
      if (key === "title" && typeof item === "string") {
        continue;
      }
      if (key === "$ref" && typeof item === "string") {
        rewritten[key] = rewriteReference(item, names);
        continue;
      }
      if ((key === "$defs" || key === "definitions") && isRecord(item)) {
        const renamed: Record<string, unknown> = {};
        for (const [definitionName, definition] of Object.entries(item)) {
          const namespacedName = names.get(definitionName) ?? `${prefix}${toTypeName(definitionName)}`;
          const rewrittenDefinition = rewrite(definition);
          renamed[namespacedName] = isRecord(rewrittenDefinition)
            ? { ...rewrittenDefinition, title: namespacedName }
            : rewrittenDefinition;
        }
        rewritten[key] = renamed;
        continue;
      }
      rewritten[key] = rewrite(item);
    }
    return rewritten;
  };

  return rewrite(structuredClone(schema)) as Record<string, unknown>;
}

function getDefinitions(schema: Record<string, unknown>): Record<string, unknown> {
  const modern = schema.$defs;
  if (isRecord(modern)) {
    return modern;
  }
  const legacy = schema.definitions;
  return isRecord(legacy) ? legacy : {};
}

function rewriteReference(reference: string, names: Map<string, string>): string {
  const match = reference.match(/^#\/(?:\$defs|definitions)\/([^/]+)$/);
  if (match === null) {
    if (reference === "#" || reference.startsWith("#/")) {
      return reference;
    }
    throw new Error(`External JSON Schema references are not supported: ${reference}`);
  }

  const key = decodePointerSegment(decodeURIComponent(match[1]));
  const renamed = names.get(key);
  if (renamed === undefined) {
    throw new Error(`JSON Schema reference points to an unknown definition: ${reference}`);
  }
  const definitionKey = reference.startsWith("#/$defs/") ? "$defs" : "definitions";
  return `#/${definitionKey}/${encodePointerSegment(renamed)}`;
}

function decodePointerSegment(value: string): string {
  return value.replaceAll("~1", "/").replaceAll("~0", "~");
}

function encodePointerSegment(value: string): string {
  return value.replaceAll("~", "~0").replaceAll("/", "~1");
}

function toTypeName(value: string): string {
  const words = value.match(/[A-Za-z0-9]+/g) ?? [];
  const name = words.map((word) => `${word.charAt(0).toUpperCase()}${word.slice(1)}`).join("") || "Tool";
  return /^\d/.test(name) ? `Tool${name}` : name;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
